<template>
  <navbar
    @search="(valueObject) => (searchObject = valueObject)"
    @clearSearch="clearSearch"
  ></navbar>
  <cards
    type="Member"
    :isMember="true"
    :members="filteredMembers"
    @sendID="(i, isTrainee) => ((index = i), (isMember = !isTrainee))"
  ></cards>
  <cards
    type="Trainee"
    :isMember="false"
    :members="filteredTrainees"
    @sendID="(i, isTrainee) => ((index = i), (isMember = !isTrainee))"
  ></cards>
  <footer-copyright></footer-copyright>

  <modal
    :type="isMember ? 'member' : 'trainee'"
    v-if="member[index] || trainee[index]"
    :nama="isMember ? member[index].nama : trainee[index].nama"
    :foto="isMember ? member[index].foto : trainee[index].foto"
    :umur="isMember ? member[index].umur : trainee[index].umur"
    :asal="isMember ? member[index].asal : trainee[index].asal"
    :generasi="isMember ? member[index].generasi : trainee[index].generasi"
    :tanggal_lahir="
      isMember ? member[index].tanggal_lahir : trainee[index].tanggal_lahir
    "
    :universitas="
      isMember ? member[index].universitas : trainee[index].universitas
    "
    :jurusan="isMember ? member[index].jurusan : trainee[index].jurusan"
  ></modal>
</template>

<script>
import axios from "axios";
import Modal from "./Modal.vue";
import Navbar from "./Navbar.vue";
import FooterCopyright from "./FooterCopyright.vue";
import GenFormat from "./GenFormat.vue";
import Cards from "./Cards.vue";
import { faL } from "@fortawesome/free-solid-svg-icons";

export default {
  components: { Modal, Navbar, Cards, GenFormat, FooterCopyright },
  data() {
    return {
      member: [],
      trainee: [],
      index: 1,
      type: true,
      isMember: true,
      searchObject: {
        nama: "",
        umur: "",
        generasi: "",
        kota_lahir: "",
        asal: "",
        universitas: "",
      },
    };
  },

  // async mounted() {
  //   try {
  //     const res = await axios.get("jkt48.member.json");
  //     this.member = res.data.member;
  //     this.trainee = res.data.trainee;
  //   } catch (error) {
  //     console.log(error);
  //   }
  //   console.log(this.member);
  //   console.log(this.trainee);
  // },

  mounted() {
    const res = {
      member: [
        {
          id: 1,
          nama: "Amanda Sukma",
          generasi: 10,
          asal: "Bandung",
          nama_panggilan: "Amanda, Manda, Mandut",
          umur: 20,
          salam_perkenalan:
            "Brum brum! Melaju cepat bagai motor 1000cc! Aku si gadis penyuka motor. Halo semuanya aku Amanda.",
          tanggal_bergabung: "18 Desember 2021",
          fanbase: "Mandaffection",
          kota_lahir: "Malang",
          tanggal_lahir: "17 December 2004",
          nama_lengkap: "Amanda Puspita Sukma Mulyadewi",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/amanda_sukma.jpg?v=20230116",
          username_idn: "Amanda JKT48",
          username_ig: "jkt48.amanda.s",
          username_sr: "Amanda / アマンダ (JKT48)",
          username_tiktok: "jkt48.amanda.s",
          username_x: "PS_AmandaJKT48",
        },
        {
          id: 2,
          nama: "Angelina Christy",
          generasi: 7,
          asal: "Jakarta",
          nama_panggilan: "Christy, Angel, Kitoy, Toya",
          umur: 19,
          salam_perkenalan:
            "Peduli dan berbaik hati, siapakah dia? Chris.. (ty!) Halo semuanya aku Christy.",
          tanggal_bergabung: "29 September 2018",
          fanbase: "Christyzer",
          kota_lahir: "Jakarta",
          tanggal_lahir: "05 December 2005",
          nama_lengkap: "Angelina Christy",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/angelina_christy.jpg?v=20230116",
          username_idn: "Christy JKT48",
          username_ig: "jkt48.christy",
          username_sr: "Christy/クリスティー (JKT48)",
          username_tiktok: "christyjkt48",
          username_x: "A_ChristyJKT48",
        },
        {
          id: 3,
          nama: "Aurellia",
          generasi: 10,
          asal: "Jakarta",
          nama_panggilan: "Lia, Oreli, Coach Lia",
          umur: 22,
          salam_perkenalan:
            "Si social butterfly yang energik dan periang! Halo semuanya nama aku Lia!",
          tanggal_bergabung: "18 Desember 2021",
          fanbase: "Liamelior",
          kota_lahir: "Jakarta",
          tanggal_lahir: "29 October 2002",
          nama_lengkap: "Aurellia",
          universitas: "Sekolah Tinggi Ilmu Ekonomi Trisakti",
          jurusan: "Akuntansi",
          foto: "https://jkt48.com/profile/aurellia.jpg?v=20230116",
          username_idn: "Lia JKT48",
          username_ig: "jkt48.aurellia_",
          username_sr: "Lia / リア (JKT48)",
          username_tiktok: "jkt48.aurellia_",
          username_x: "AU_LiaJKT48",
        },
        {
          id: 4,
          nama: "Azizi Asadel",
          generasi: 7,
          asal: "Tangerang",
          nama_panggilan: "Zee, Azizi, Zizoy, Zoya",
          umur: 20,
          salam_perkenalan:
            "Si gadis tomboi yang semangatnya meletup-letup! Panggil aku Zee!",
          tanggal_bergabung: "29 September 2018",
          fanbase: "Zeemotion",
          kota_lahir: "Jakarta",
          tanggal_lahir: "16 May 2004",
          nama_lengkap: "Azizi Shafaa Asadel",
          universitas: "Universitas Terbuka",
          jurusan: "Ilmu Komunikasi",
          foto: "https://jkt48.com/profile/azizi_asadel.jpg?v=20230116",
          username_idn: "Zee JKT48",
          username_ig: "jkt48.zee",
          username_sr: "Zee/ジー (JKT48)",
          username_tiktok: "zeejkt48",
          username_x: "A_ZeeJKT48",
        },
        {
          id: 5,
          nama: "Callista Alifia",
          generasi: 10,
          asal: "Jakarta",
          nama_panggilan: "Callie, Keli",
          umur: 19,
          salam_perkenalan:
            "Si beruang madu, penyuka madu! Hai semuanya aku Callie!",
          tanggal_bergabung: "18 Desember 2021",
          fanbase: "Callistavers",
          kota_lahir: "Jakarta",
          tanggal_lahir: "08 August 2005",
          nama_lengkap: "Callista Alifia Wardhana",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/callista_alifia.jpg?v=20230116",
          username_idn: "Callie JKT48",
          username_ig: "jkt48.callie.a",
          username_sr: "Callie / カリー (JKT48)",
          username_tiktok: "jkt48.callie.a",
          username_x: "AW_CallieJKT48",
        },
        {
          id: 6,
          nama: "Cornelia Vanisa",
          generasi: 8,
          asal: "Tangerang",
          nama_panggilan: "Oniel",
          umur: 22,
          salam_perkenalan:
            "Seperti teka-teki yang akan membuat kalian selalu penasaran denganku! Aku Oniel!",
          tanggal_bergabung: "27 April 2019",
          fanbase: "Onielity",
          kota_lahir: "Tangerang",
          tanggal_lahir: "26 July 2002",
          nama_lengkap: "Cornelia Syafa Vanisa",
          universitas: "Universitas Pamulang",
          jurusan: "Sastra Inggris",
          foto: "https://jkt48.com/profile/cornelia_vanisa.jpg?v=20230116",
          username_idn: "Oniel JKT48",
          username_ig: "jkt48.oniel",
          username_sr: "Oniel / オニエル (JKT48)",
          username_tiktok: "onieljkt48",
          username_x: "C_OnielJKT48",
        },
        {
          id: 7,
          nama: "Febriola Sinambela",
          generasi: 7,
          asal: "Jakarta",
          nama_panggilan: "Olla, Olali, Febri",
          umur: 19,
          salam_perkenalan:
            "Dengan keajaibanku aku akan membuat kalian semua selalu tertawa! Halo semuanya aku Olla, si mechanic girl!",
          tanggal_bergabung: "29 September 2018",
          fanbase: "Oracle (Olla the Miracle)",
          kota_lahir: "Jakarta",
          tanggal_lahir: "26 February 2005",
          nama_lengkap: "Febriola Sinambela",
          universitas: "Universitas Nasional",
          jurusan: "Ilmu Komunikasi",
          foto: "https://jkt48.com/profile/febriola_sinambela.jpg?v=20230116",
          username_idn: "Olla JKT48",
          username_ig: "jkt48.olla",
          username_sr: "Olla / オラ (JKT48)",
          username_tiktok: "ollajkt48",
          username_x: "F_OllaJKT48",
        },
        {
          id: 8,
          nama: "Feni Fitriyanti",
          generasi: 3,
          asal: "Cianjur",
          nama_panggilan: "Feni, Mpen",
          umur: 25,
          salam_perkenalan:
            "Matahari yang indah, yang akan memberikan kehangatan di setiap harinya. Halo aku Feni.",
          tanggal_bergabung: "15 Maret 2014",
          fanbase: "Fenidelity",
          kota_lahir: "Cianjur",
          tanggal_lahir: "16 January 1999",
          nama_lengkap: "Feni Fitriyanti",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/feni_fitriyanti.jpg?v=20230116",
          username_idn: "Feni JKT48",
          username_ig: "jkt48feni",
          username_sr: "Feni / フェニ (JKT48)",
          username_tiktok: "fenijkt48",
          username_x: "F_FeniJKT48",
        },
        {
          id: 9,
          nama: "Fiony Alveria",
          generasi: 8,
          asal: "Tangerang",
          nama_panggilan: "Fiony, Pio, Ce Pio",
          umur: 22,
          salam_perkenalan:
            "Seperti simfoni yang menenangkan hati, halo aku Fiony!",
          tanggal_bergabung: "27 April 2019",
          fanbase: "Symfiony",
          kota_lahir: "Jakarta",
          tanggal_lahir: "04 February 2002",
          nama_lengkap: "Fiony Alveria Tantri",
          universitas: "Universitas Pelita Harapan",
          jurusan: "Desain Komunikasi Visual",
          foto: "https://jkt48.com/profile/fiony_alveria.jpg?v=20230116",
          username_idn: "Fiony JKT48",
          username_ig: "jkt48.fiony",
          username_sr: "Fiony / フィオニー (JKT48)",
          username_tiktok: "fionyjkt48",
          username_x: "A_FionyJKT48",
        },
        {
          id: 10,
          nama: "Flora Shafiq",
          generasi: 8,
          asal: "Tangerang",
          nama_panggilan: "Flora, Flo",
          umur: 19,
          salam_perkenalan:
            "Mau ikut aku nggak? (Mau!) Ayo ikut ke dunia Flora! Simsalabim akan 'ku sulap hatimu menjadi berbunga-bunga! Halo semuanya, aku Flora!",
          tanggal_bergabung: "27 April 2019",
          fanbase: "FloRisen",
          kota_lahir: "Tangerang",
          tanggal_lahir: "04 April 2005",
          nama_lengkap: "Flora Shafiqa Riyadi",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/flora_shafiq.jpg?v=20230116",
          username_idn: "Flora JKT48",
          username_ig: "jkt48.flora",
          username_sr: "Flora / フロラ (JKT48)",
          username_tiktok: "florajkt48",
          username_x: "S_FloraJKT48",
        },
        {
          id: 11,
          nama: "Freya Jayawardana",
          generasi: 7,
          asal: "Tangerang",
          nama_panggilan: "Freya, Fre, Nurdana, Nunung",
          umur: 18,
          salam_perkenalan:
            "Gadis koleris yang suka berimajinasi, terangi harimu dengan senyuman karamelku. Halo aku Freya!",
          tanggal_bergabung: "29 September 2018",
          fanbase: "Freyanation",
          kota_lahir: "Tangerang",
          tanggal_lahir: "13 February 2006",
          nama_lengkap: "Freyanashifa Jayawardana",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/freya_jayawardana.jpg?v=20230116",
          username_idn: "Freya JKT48",
          username_ig: "jkt48.freya",
          username_sr: "Freya / フレヤ (JKT48)",
          username_tiktok: "freyajkt48",
          username_x: "Freya_JKT48",
        },
        {
          id: 12,
          nama: "Gabriela Abigail",
          generasi: 10,
          asal: "Jakarta",
          nama_panggilan: "Ella, Gaby, Ellay",
          umur: 18,
          salam_perkenalan:
            "Ohayo! Konnichiwa! Oyasumi! Aku ingin ada di setiap harimu. Halo semuanya aku Ella.",
          tanggal_bergabung: "18 Desember 2021",
          fanbase: "Ellatheria",
          kota_lahir: "Jakarta",
          tanggal_lahir: "07 August 2006",
          nama_lengkap: "Gabriela Abigail Mewengkang",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/gabriela_abigail.jpg?v=20230116",
          username_idn: "Ella JKT48",
          username_ig: "jkt48.ella.a",
          username_sr: "Ella / エラ (JKT48)",
          username_tiktok: "jkt48.ella.a",
          username_x: "AM_EllaJKT48",
        },
        {
          id: 13,
          nama: "Gita Sekar Andarini",
          generasi: 6,
          asal: "Jakarta",
          nama_panggilan: "Gita",
          umur: 23,
          salam_perkenalan: "Diam bukan berarti tak memperhatikanmu. Aku Gita.",
          tanggal_bergabung: "08 April 2018",
          fanbase: "Gitroops",
          kota_lahir: "Jakarta",
          tanggal_lahir: "30 June 2001",
          nama_lengkap: "Gita Sekar Andarini",
          universitas: "Universitas Nasional",
          jurusan: "Sastra Inggris",
          foto: "https://jkt48.com/profile/gita_sekar_andarini.jpg?v=20230116",
          username_idn: "Gita JKT48",
          username_ig: "jkt48gita",
          username_sr: "Gita / ギタ (JKT48)",
          username_tiktok: "gitajkt48",
          username_x: "A_GitaJKT48",
        },
        {
          id: 14,
          nama: "Grace Octaviani",
          generasi: 11,
          asal: "Jakarta",
          nama_panggilan: "Gracie",
          umur: 17,
          salam_perkenalan:
            "Manis seperti gulali, imut seperti kelinci. Cie cie cie Gracie!",
          tanggal_bergabung: "31 Oktober 2022",
          fanbase: "Gracyluv",
          kota_lahir: "Tangerang",
          tanggal_lahir: "18 October 2007",
          nama_lengkap: "Grace Octaviani Tanujaya",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/grace_octaviani.jpg?v=20230116",
          username_idn: "Gracie JKT48",
          username_ig: "@jkt48.gracie",
          username_sr: "Gracie / グラシー (JKT48)",
          username_tiktok: "@graciejkt48",
          username_x: "@Gracie_JKT48",
        },
        {
          id: 15,
          nama: "Greesella Adhalia",
          generasi: 11,
          asal: "Jakarta",
          nama_panggilan: "Greesel, Icel",
          umur: 18,
          salam_perkenalan:
            "Pandangan mataku akan menyinari hatimu bagaikan kunang-kunang di malam hari. Halo, aku Greesel!",
          tanggal_bergabung: "31 Oktober 2022",
          fanbase: "Degrees",
          kota_lahir: "Bogor",
          tanggal_lahir: "10 January 2006",
          nama_lengkap: "Greesella Sophina Adhalia",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/greesella_adhalia.jpg?v=20230116",
          username_idn: "Greesel JKT48",
          username_ig: "@jkt48.greesel",
          username_sr: "Greesel / グリーセル (JKT48)",
          username_tiktok: "@greeseljkt48",
          username_x: "@Greesel_JKT48",
        },
        {
          id: 16,
          nama: "Helisma Putri",
          generasi: 7,
          asal: "Bandung",
          nama_panggilan: "Eli, Helisma, Ceu Eli",
          umur: 24,
          salam_perkenalan:
            "Aprikot aprikot aprikot aprikot, pang! Dengan energi kegembiraanku aku akan menghangatkan suasana. Halo halo aku Ceu Eli.",
          tanggal_bergabung: "29 September 2018",
          fanbase: "Helismiley",
          kota_lahir: "Bandung",
          tanggal_lahir: "15 June 2000",
          nama_lengkap: "Helisma Mauludzunia Putri Kurnia",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/helisma_putri.jpg?v=20230116",
          username_idn: "Eli JKT48",
          username_ig: "jkt48.eli",
          username_sr: "Eli / エリ (JKT48)",
          username_tiktok: "elijkt48",
          username_x: "H_EliJKT48",
        },
        {
          id: 17,
          nama: "Indah Cahya",
          generasi: 9,
          asal: "Kerinci",
          nama_panggilan: "Indah",
          umur: 23,
          salam_perkenalan:
            "Tak banyak bicara, bercerita melalui tulisan. Hai aku Indah.",
          tanggal_bergabung: "1 Desember 2019",
          fanbase: "Interindah",
          kota_lahir: "Jambi",
          tanggal_lahir: "20 March 2001",
          nama_lengkap: "Indah Cahya Nabilla",
          universitas: "Universitas Negeri Jakarta",
          jurusan: "Pendidikan Bahasa Inggris",
          foto: "https://jkt48.com/profile/indah_cahya.jpg?v=20230116",
          username_idn: "Indah JKT48",
          username_ig: "jkt48indah_",
          username_sr: "Indah / インダー (JKT48)",
          username_tiktok: "indahjkt48",
          username_x: "C_IndahJKT48",
        },
        {
          id: 18,
          nama: "Indira Seruni",
          generasi: 10,
          asal: "Bandung",
          nama_panggilan: "Indira, Dira",
          umur: 20,
          salam_perkenalan:
            "Watashi no kokoro unlock, akan menemani hari-harimu dengan sepenuh hati. Halo, aku Indira!",
          tanggal_bergabung: "18 Desember 2021",
          fanbase: "Indiraise",
          kota_lahir: "Bandung",
          tanggal_lahir: "26 April 2004",
          nama_lengkap: "Indira Putri Seruni",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/indira_seruni.jpg?v=20230116",
          username_idn: "Indira JKT48",
          username_ig: "jkt48.indira.s",
          username_sr: "Indira / インディラ (JKT48)",
          username_tiktok: "jkt48.indira.s",
          username_x: "SP_IndiraJKT48",
        },
        {
          id: 19,
          nama: "Jessica Chandra",
          generasi: 7,
          asal: "Tangerang",
          nama_panggilan: "Jessi, Jeci",
          umur: 19,
          salam_perkenalan:
            "Suka menari dan akan selalu berusaha untuk menjadi sumber energimu. Perkenalkan aku Jessi.",
          tanggal_bergabung: "29 September 2018",
          fanbase: "Jessination",
          kota_lahir: "Jakarta",
          tanggal_lahir: "23 September 2005",
          nama_lengkap: "Jessica Chandra",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/jessica_chandra.jpg?v=20230116",
          username_idn: "Jessi JKT48",
          username_ig: "jkt48.jessi",
          username_sr: "Jessi / ジェシ (JKT48)",
          username_tiktok: "jessijkt48",
          username_x: "C_JessiJKT48",
        },
        {
          id: 20,
          nama: "Jesslyn Elly",
          generasi: 10,
          asal: "Jakarta",
          nama_panggilan: "Lyn",
          umur: 23,
          salam_perkenalan:
            "Seperti ombak laut yang tenang, tiba-tiba aku akan menyapumu dengan banyak cinta. Halo semuanya, aku Lyn!",
          tanggal_bergabung: "18 Desember 2021",
          fanbase: "Lynear",
          kota_lahir: "Jakarta",
          tanggal_lahir: "13 September 2001",
          nama_lengkap: "Jesslyn Elly Septiani",
          universitas: "Universitas Pelita Harapan",
          jurusan: "Psikologi",
          foto: "https://jkt48.com/profile/jesslyn_elly.jpg?v=20230116",
          username_idn: "Lyn JKT48",
          username_ig: "jkt48.lyn.s",
          username_sr: "Lyn / リーン (JKT48)",
          username_tiktok: "jkt48.lyn.s",
          username_x: "SE_LynJKT48",
        },
        {
          id: 21,
          nama: "Kathrina Irene",
          generasi: 9,
          asal: "Jakarta",
          nama_panggilan: "Kathrina, Kathrin, Atin, Bokem",
          umur: 18,
          salam_perkenalan:
            "Never miss a chance to be a star. Halo semua aku Kathrina.",
          tanggal_bergabung: "1 Desember 2019",
          fanbase: "KATH, Inc.",
          kota_lahir: "Bekasi",
          tanggal_lahir: "26 July 2006",
          nama_lengkap: "Kathrina Irene Indarto Putri",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/kathrina_irene.jpg?v=20230116",
          username_idn: "Kathrina JKT48",
          username_ig: "jkt48.kathrina",
          username_sr: "Kathrina / カトリナ (JKT48)",
          username_tiktok: "kathrinjkt48",
          username_x: "I_KathrinaJKT48",
        },
        {
          id: 22,
          nama: "Lulu Salsabila",
          generasi: 8,
          asal: "Serang",
          nama_panggilan: "Lulu, Salsa",
          umur: 22,
          salam_perkenalan:
            "Terang seperti bulan, bersinar seperti bintang. Halo aku Lulu!",
          tanggal_bergabung: "27 April 2019",
          fanbase: "Lunarian",
          kota_lahir: "Serang",
          tanggal_lahir: "23 October 2002",
          nama_lengkap: "Lulu Azkiya Salsabila",
          universitas: "Universitas Paramadina",
          jurusan: "Ilmu Komunikasi",
          foto: "https://jkt48.com/profile/lulu_salsabila.jpg?v=20230116",
          username_idn: "Lulu JKT48",
          username_ig: "jkt48.lulu",
          username_sr: "Lulu / ルル (JKT48)",
          username_tiktok: "lulu_jkt48",
          username_x: "A_LuluJKT48",
        },
        {
          id: 23,
          nama: "Marsha Lenathea",
          generasi: 9,
          asal: "Jakarta",
          nama_panggilan: "Marsha, Matcha, Anime, Maeng",
          umur: 18,
          salam_perkenalan:
            "Seperti pizza yang selalu dinanti-nantikan semua orang, selalu nantikan aku ya! Halo aku Marsha!",
          tanggal_bergabung: "1 Desember 2019",
          fanbase: "MarshaOshi",
          kota_lahir: "Jakarta",
          tanggal_lahir: "09 January 2006",
          nama_lengkap: "Marsha Lenathea Lapian",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/marsha_lenathea.jpg?v=20230116",
          username_idn: "Marsha JKT48",
          username_ig: "jkt48.marsha",
          username_sr: "Marsha / マーシャ (JKT48)",
          username_tiktok: "marsha.jkt48",
          username_x: "L_MarshaJKT48",
        },
        {
          id: 24,
          nama: "Mutiara Azzahra",
          generasi: 7,
          asal: "Jakarta",
          nama_panggilan: "Muthe, Mumuchang",
          umur: 20,
          salam_perkenalan:
            "Dengan kelincahanku, aku akan menari setiap hari! Panggil aku Mu-Mu-Mu-Mu-the!",
          tanggal_bergabung: "29 September 2018",
          fanbase: "Muffin",
          kota_lahir: "Jakarta",
          tanggal_lahir: "12 June 2004",
          nama_lengkap: "Mutiara Azzahra Umandana",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/mutiara_azzahra.jpg?v=20230116",
          username_idn: "Muthe JKT48",
          username_ig: "jkt48.muthe_",
          username_sr: "Muthe / ムテ (JKT48)",
          username_tiktok: "muthejkt48",
          username_x: "A_MutheJKT48",
        },
        {
          id: 25,
          nama: "Raisha Syifa",
          generasi: 10,
          asal: "Jakarta",
          nama_panggilan: "Raisha",
          umur: 17,
          salam_perkenalan:
            "Kalau sakura itu kembang, aku itu kembanggaanmu! You can call me Raisha.",
          tanggal_bergabung: "18 Desember 2021",
          fanbase: "Raishanrise",
          kota_lahir: "Tangerang",
          tanggal_lahir: "11 November 2007",
          nama_lengkap: "Raisha Syifa Wardhana",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/raisha_syifa.jpg?v=20230116",
          username_idn: "Raisha JKT48",
          username_ig: "jkt48.raisha.s",
          username_sr: "Raisha / ライシャ (JKT48)",
          username_tiktok: "jkt48.raisha.s",
          username_x: "SW_RaishaJKT48",
        },
        {
          id: 26,
          nama: "Reva Fidela",
          generasi: 8,
          asal: "Jakarta",
          nama_panggilan: "Adel, Dedel, Reva",
          umur: 18,
          salam_perkenalan:
            "Bagaikan kucing yang kalem tapi akan selalu memikat hati kamu! Halo semuanya aku Adel!",
          tanggal_bergabung: "27 April 2019",
          fanbase: "Adellion",
          kota_lahir: "Jakarta",
          tanggal_lahir: "14 July 2006",
          nama_lengkap: "Reva Fidela Adel Pantjoro",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/reva_fidela.jpg?v=20230116",
          username_idn: "Adel JKT48",
          username_ig: "jkt48.adel",
          username_sr: "Adel / アデル (JKT48)",
          username_tiktok: "adeljkt48",
          username_x: "R_AdelJKT48",
        },
        {
          id: 27,
          nama: "Shani Indira Natio",
          generasi: 3,
          asal: "Yogyakarta",
          nama_panggilan: "Shani",
          umur: 26,
          salam_perkenalan: "Semanis coklat selembut sutra. Halo aku Shani.",
          tanggal_bergabung: "15 Maret 2014",
          fanbase: "Inshanity",
          kota_lahir: "Kebumen",
          tanggal_lahir: "05 October 1998",
          nama_lengkap: "Shani Indira Natio",
          universitas: "Universitas Tarumanegara",
          jurusan: "Ilmu Komunikasi",
          foto: "https://jkt48.com/profile/shani_indira_natio.jpg?v=20230116",
          username_idn: "Shani JKT48",
          username_ig: "jkt48shani",
          username_sr: "Shani / シャニ (JKT48)",
          username_tiktok: "shanijkt48",
          username_x: "N_ShaniJKT48",
        },
        {
          id: 28,
          nama: "Shania Gracia",
          generasi: 3,
          asal: "Jakarta",
          nama_panggilan: "Gracia, Gre",
          umur: 25,
          salam_perkenalan:
            "Senyumku terekam jelas dalam ingatanmu seperti foto dengan sejuta warna. Namaku Gracia, always smile! Sekali lagi? (Gracia!)",
          tanggal_bergabung: "15 Maret 2014",
          fanbase: "Gracias",
          kota_lahir: "Jakarta",
          tanggal_lahir: "31 August 1999",
          nama_lengkap: "Shania Gracia",
          universitas: "Institut Bisnis Dan Informatika Kwik Kian Gie",
          jurusan: "Ilmu Komunikasi",
          foto: "https://jkt48.com/profile/shania_gracia.jpg?v=20230116",
          username_idn: "Gracia JKT48",
          username_ig: "jkt48gracia",
          username_sr: "Gracia / グラシア (JKT48)",
          username_tiktok: "graciajkt48",
          username_x: "S_GraciaJKT48",
        },
      ],
      trainee: [
        {
          id: 0,
          nama: "Abigail Rachel",
          generasi: 12,
          asal: "Jakarta",
          nama_panggilan: "Aralie",
          umur: 16,
          salam_perkenalan:
            "Seperti bunga yang mekar, aku akan membuat kamu, kamu, dan kamu terbayang-bayang. Aku Ara-Aralie. Halo semuanya, nama aku Aralie ya!",
          tanggal_bergabung: "18 November 2023",
          fanbase: "Aralie",
          kota_lahir: "Jakarta",
          tanggal_lahir: "06 August 2008",
          nama_lengkap: "Abigail Rachelie",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/abigail_rachel.jpg?v=20230116",
          username_ig: "@jkt48.aralie",
          username_tiktok: "@jkt48.aralie",
          username_x: "@Aralie_JKT48",
        },
        {
          id: 1,
          nama: "Adeline Wijaya",
          generasi: 12,
          asal: "Jakarta",
          nama_panggilan: "Delynn",
          umur: 17,
          salam_perkenalan:
            "Nyemangatin dan ngangenin, siapa yang kamu pikirin? Delynn! Pyong! Pyong! Aku Delynn!",
          tanggal_bergabung: "18 November 2023",
          fanbase: "Adeliner",
          kota_lahir: "Jakarta",
          tanggal_lahir: "01 September 2007",
          nama_lengkap: "Adeline Wijaya",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/adeline_wijaya.jpg?v=20230116",
          username_ig: "@jkt48.delynn",
          username_tiktok: "@jkt48.delynn",
          username_x: "@Delynn_JKT48",
        },
        {
          id: 2,
          nama: "Aisa Maharani",
          generasi: 12,
          asal: "Medan",
          nama_panggilan: "Shasa",
          umur: 18,
          salam_perkenalan:
            "Horas we! Gadis ceria yang akan membawamu ke dunia keajaiban penuh warna. Halo, panggil aku Shasa!",
          tanggal_bergabung: "18 November 2023",
          fanbase: "Aisareine",
          kota_lahir: "Medan",
          tanggal_lahir: "31 January 2006",
          nama_lengkap: "Aisa Maharani Napitupulu",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/aisa_maharani.jpg?v=20230116",
          username_ig: "@jkt48.shasa",
          username_tiktok: "@jkt48.shasa",
          username_x: "@Shasa_JKT48",
        },
        {
          id: 3,
          nama: "Alya Amanda",
          generasi: 11,
          asal: "Jakarta",
          nama_panggilan: "Alya",
          umur: 18,
          salam_perkenalan:
            "Jika hatimu sedang menangis, aku akan datang sebagai pelangi! Hai aku Alya!",
          tanggal_bergabung: "31 Oktober 2022",
          fanbase: "Alamanda",
          kota_lahir: "Jakarta",
          tanggal_lahir: "26 August 2006",
          nama_lengkap: "Alya Amanda Fatihah",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/alya_amanda.jpg?v=20230116",
          username_idn: "Alya JKT48",
          username_ig: "@jkt48.alya_",
          username_sr: "Alya / アリア (JKT48)",
          username_tiktok: "@alyajkt48",
          username_x: "@AA_AlyaJKT48",
        },
        {
          id: 4,
          nama: "Anindya Ramadhani",
          generasi: 11,
          asal: "Jakarta",
          nama_panggilan: "Anindya, Anin",
          umur: 19,
          salam_perkenalan: "Si mungil hadir, semanis mangga! Hai aku Anindya!",
          tanggal_bergabung: "31 Oktober 2022",
          fanbase: "Aninimous",
          kota_lahir: "Depok",
          tanggal_lahir: "18 October 2005",
          nama_lengkap: "Anindya Ramadhani Purnomo",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/anindya_ramadhani.jpg?v=20230116",
          username_idn: "Anindya JKT48",
          username_ig: "@jkt48.anindya_",
          username_sr: "Anindya / アニンディア (JKT48)",
          username_tiktok: "@anindyajkt48",
          username_x: "@AR_AnindyaJKT48",
        },
        {
          id: 5,
          nama: "Aurhel Alana",
          generasi: 12,
          asal: "Bekasi",
          nama_panggilan: "Lana",
          umur: 18,
          salam_perkenalan:
            "Dengan kekuatan bulan, aku akan menyihirmu dengan pesonaku! Halo semuanya, nama aku Lana!",
          tanggal_bergabung: "18 November 2023",
          fanbase: "Lanautica",
          kota_lahir: "Bekasi",
          tanggal_lahir: "14 September 2006",
          nama_lengkap: "Aurhel Alana",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/aurhel_alana.jpg?v=20230116",
          username_ig: "@jkt48.lana.a",
          username_tiktok: "@jkt48.lana",
          username_x: "@AR_LanaJKT48",
        },
        {
          id: 6,
          nama: "Catherina Vallencia",
          generasi: 12,
          asal: "Bekasi",
          nama_panggilan: "Erine",
          umur: 17,
          salam_perkenalan:
            "Hanya dengan seribu kejutan, checkmate! Siap memenangkan hatimu! Halo semuanya namaku Erine!",
          tanggal_bergabung: "18 November 2023",
          fanbase: "Cavallery",
          kota_lahir: "Bekasi",
          tanggal_lahir: "21 August 2007",
          nama_lengkap: "Catherina Vallencia Kurniawan",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/catherina_vallencia.jpg?v=20230116",
          username_ig: "@jkt48.erine",
          username_tiktok: "@jkt48.erine_",
          username_x: "@CErine_JKT48",
        },
        {
          id: 7,
          nama: "Cathleen Nixie",
          generasi: 11,
          asal: "Jakarta",
          nama_panggilan: "Cathy",
          umur: 15,
          salam_perkenalan:
            "Tring! Si peri cantik jelita, itulah aku! Hai semuanya, namaku Cathy!",
          tanggal_bergabung: "31 Oktober 2022",
          fanbase: "Cathleennexus",
          kota_lahir: "Surabaya",
          tanggal_lahir: "28 May 2009",
          nama_lengkap: "Cathleen Hana Nixie",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/cathleen_nixie.jpg?v=20230116",
          username_idn: "Cathy JKT48",
          username_ig: "@jkt48.cathy",
          username_sr: "Cathy / キャシー (JKT48)",
          username_tiktok: "@cathyjkt48",
          username_x: "@N_CathyJKT48",
        },
        {
          id: 8,
          nama: "Celline Thefani",
          generasi: 11,
          asal: "Jakarta",
          nama_panggilan: "Elin",
          umur: 17,
          salam_perkenalan:
            "Semanis permen kapas dan seindah bunga lavender. Hola, perkenalkan namaku Elin.",
          tanggal_bergabung: "31 Oktober 2022",
          fanbase: "Cellineyours",
          kota_lahir: "Tangerang",
          tanggal_lahir: "09 April 2007",
          nama_lengkap: "Celline Thefannie",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/celline_thefani.jpg?v=20230116",
          username_idn: "Elin JKT48",
          username_ig: "@jkt48.elin_",
          username_sr: "Elin / エリン (JKT48)",
          username_tiktok: "@elinjkt48",
          username_x: "@Elin_JKT48",
        },
        {
          id: 9,
          nama: "Chelsea Davina",
          generasi: 11,
          asal: "Sydney",
          nama_panggilan: "Chelsea",
          umur: 15,
          salam_perkenalan:
            "As bright as a shooting star in the starry night sky. Hai semua, aku Chelsea!",
          tanggal_bergabung: "31 Oktober 2022",
          fanbase: "Chelsealand",
          kota_lahir: "Sydney",
          tanggal_lahir: "23 December 2009",
          nama_lengkap: "Chelsea Davina Norman",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/chelsea_davina.jpg?v=20230116",
          username_idn: "Chelsea JKT48",
          username_ig: "@jkt48.chelsea.d",
          username_sr: "Chelsea / チェルシー (JKT48)",
          username_tiktok: "@_chelseajkt48",
          username_x: "@DC_ChelseaJKT48",
        },
        {
          id: 10,
          nama: "Cynthia Yaputera",
          generasi: 11,
          asal: "Jakarta",
          nama_panggilan: "Cynthia, Ciput",
          umur: 21,
          salam_perkenalan:
            "Semangatku terus-menerus meluap, pop-pop! Halo aku Cynthia yang selalu semangat!",
          tanggal_bergabung: "31 Oktober 2022",
          fanbase: "Cynthiaction",
          kota_lahir: "Jakarta",
          tanggal_lahir: "22 November 2003",
          nama_lengkap: "Cynthia Yaputera",
          universitas: "Universitas Bina Nusantara",
          jurusan: "Desain Interior",
          foto: "https://jkt48.com/profile/cynthia_yaputera.jpg?v=20230116",
          username_idn: "Cynthia JKT48",
          username_ig: "@jkt48.cynthia",
          username_sr: "Cynthia / シンティア (JKT48)",
          username_tiktok: "@cynthiajkt48",
          username_x: "@Y_CynthiaJKT48",
        },
        {
          id: 11,
          nama: "Dena Natalia",
          generasi: 11,
          asal: "Bandung",
          nama_panggilan: "Danella, Dena",
          umur: 19,
          salam_perkenalan:
            "Tok tok! Siapa? Si penari yang akan menarikmu ke duniaku. Hai, aku Danella.",
          tanggal_bergabung: "31 Oktober 2022",
          fanbase: "Denalize",
          kota_lahir: "Bekasi",
          tanggal_lahir: "16 December 2005",
          nama_lengkap: "Dena Natalia",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/dena_natalia.jpg?v=20230116",
          username_idn: "Danella JKT48",
          username_ig: "@jkt48.danella",
          username_sr: "Danella / ダネラ (JKT48)",
          username_tiktok: "@danellajkt48",
          username_x: "@Danella_JKT48",
        },
        {
          id: 12,
          nama: "Desy Natalia",
          generasi: 11,
          asal: "Bandung",
          nama_panggilan: "Daisy, Desy",
          umur: 19,
          salam_perkenalan:
            "Seperti bunga daisy, aku akan memancarkan kesegaran dan kebahagiaan! Hai hai, aku Daisy.",
          tanggal_bergabung: "31 Oktober 2022",
          fanbase: "Daisynateur",
          kota_lahir: "Bekasi",
          tanggal_lahir: "16 December 2005",
          nama_lengkap: "Desy Natalia",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/desy_natalia.jpg?v=20230116",
          username_idn: "Daisy JKT48",
          username_ig: "@jkt48.daisy",
          username_sr: "Daisy / デイシー (JKT48)",
          username_tiktok: "@daisyjkt48",
          username_x: "@Daisy_JKT48",
        },
        {
          id: 13,
          nama: "Fritzy Rosmerian",
          generasi: 12,
          asal: "Jakarta",
          nama_panggilan: "Fritzy",
          umur: 16,
          salam_perkenalan:
            "Abrakadabra! Si pesulap yang siap membuat hatimu terpikat. Halo semuanya, it's me Fritzy.",
          tanggal_bergabung: "18 November 2023",
          fanbase: "Itzyraise",
          kota_lahir: "Jakarta",
          tanggal_lahir: "28 July 2008",
          nama_lengkap: "Fritzy Rosmerian",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/fritzy_rosmerian.jpg?v=20230116",
          username_ig: "@jkt48.fritzy.r",
          username_tiktok: "@jkt48.fritzy",
          username_x: "@RFritzy_JKT48",
        },
        {
          id: 14,
          nama: "Gendis Mayrannisa",
          generasi: 11,
          asal: "Jakarta",
          nama_panggilan: "Gendis",
          umur: 14,
          salam_perkenalan:
            "Bonjour! Periang dan pencair suasana, itulah aku. Halo semuanya, aku Gendis!",
          tanggal_bergabung: "31 Oktober 2022",
          fanbase: "Gendiscious",
          kota_lahir: "Jakarta",
          tanggal_lahir: "23 June 2010",
          nama_lengkap: "Gendis Mayrannisa Setiawan",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/gendis_mayrannisa.jpg?v=20230116",
          username_idn: "Gendis JKT48",
          username_ig: "@jkt48.gendis",
          username_sr: "Gendis / ゲンディス (JKT48)",
          username_tiktok: "@gendisjkt48",
          username_x: "@Gendis_JKT48",
        },
        {
          id: 17,
          nama: "Hillary Abigail",
          generasi: 12,
          asal: "Jakarta",
          nama_panggilan: "Lily",
          umur: 17,
          salam_perkenalan:
            "Papipapipum! Aku akan mengejutkanmu dengan kehebatanku! Halo nama aku Lily.",
          tanggal_bergabung: "18 November 2023",
          fanbase: "Hillaryours",
          kota_lahir: "Jakarta",
          tanggal_lahir: "19 October 2007",
          nama_lengkap: "Hillary Abigail",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/hillary_abigail.jpg?v=20230116",
          username_ig: "@jkt48.lily_",
          username_tiktok: "@jkt48.lily",
          username_x: "@Lily_JKT48",
        },
        {
          id: 18,
          nama: "Jazzlyn Trisha",
          generasi: 12,
          asal: "Jakarta",
          nama_panggilan: "Trisha",
          umur: 13,
          salam_perkenalan:
            "Pelukis yang hadir di mimpi-mimpi indahmu. One, two, Tri... sha!",
          tanggal_bergabung: "18 November 2023",
          fanbase: "Trishairs",
          kota_lahir: "Jakarta",
          tanggal_lahir: "16 October 2011",
          nama_lengkap: "Jazzlyn Trisha",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/jazzlyn_trisha.jpg?v=20230116",
          username_ig: "@jkt48.trisha",
          username_tiktok: "@jkt48.trisha",
          username_x: "@JTrisha_JKT48",
        },
        {
          id: 19,
          nama: "Jeane Victoria",
          generasi: 11,
          asal: "Jakarta",
          nama_panggilan: "Jeane, Kajen",
          umur: 18,
          salam_perkenalan:
            "Victoria! Aku akan memenangkan harimu. Hai, aku Jeane!",
          tanggal_bergabung: "31 Oktober 2022",
          fanbase: "Jeanity",
          kota_lahir: "Tangerang",
          tanggal_lahir: "05 June 2006",
          nama_lengkap: "Jeane Victoria Kurniawan",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/jeane_victoria.jpg?v=20230116",
          username_idn: "Jeane JKT48",
          username_ig: "@jkt48.jeane",
          username_sr: "Jeane / ジーン (JKT48)",
          username_tiktok: "@jeanejkt48",
          username_x: "@Jeane_JKT48",
        },
        {
          id: 20,
          nama: "Letycia Moreen",
          generasi: 12,
          asal: "Jakarta",
          nama_panggilan: "Moreen",
          umur: 14,
          salam_perkenalan:
            "Sweet as bubble gum, graceful as a princess. Siapakah itu? One and only, Moreen! Halo semuanya nama aku Moreen!",
          tanggal_bergabung: "18 November 2023",
          fanbase: "Morrealta",
          kota_lahir: "Jakarta",
          tanggal_lahir: "07 June 2010",
          nama_lengkap: "Letycia Moreen Felithia",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/letycia_moreen.jpg?v=20230116",
          username_ig: "@jkt48.moreen",
          username_tiktok: "@jkt48.moreen",
          username_x: "@Moreen_JKT48",
        },
        {
          id: 21,
          nama: "Michelle Alexandra",
          generasi: 11,
          asal: "Palembang",
          nama_panggilan: "Michie",
          umur: 15,
          salam_perkenalan:
            "Always your number one, till infinity and beyond. Hello everyone, it's Michie!",
          tanggal_bergabung: "31 Oktober 2022",
          fanbase: "Michiban",
          kota_lahir: "Jakarta",
          tanggal_lahir: "22 April 2009",
          nama_lengkap: "Michelle Alexandra Suandi",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/michelle_alexandra.jpg?v=20230116",
          username_idn: "Michie JKT48",
          username_ig: "@jkt48.michie_",
          username_sr: "Michie / ミチー (JKT48)",
          username_tiktok: "@michiejkt48",
          username_x: "@Michie_JKT48",
        },
        {
          id: 22,
          nama: "Michelle Levia",
          generasi: 12,
          asal: "Tangerang",
          nama_panggilan: "Levi",
          umur: 15,
          salam_perkenalan:
            "Are you ready? Jalani hari ini dengan menari bersamaku. Yuhu! Aku Levi!",
          tanggal_bergabung: "18 November 2023",
          fanbase: "Levianistic",
          kota_lahir: "Kota Tangerang",
          tanggal_lahir: "24 January 2009",
          nama_lengkap: "Michelle Levia Arifin",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/michelle_levia.jpg?v=20230116",
          username_ig: "@jkt48.levi",
          username_tiktok: "@jkt48.levi",
          username_x: "@Levi_JKT48",
        },
        {
          id: 23,
          nama: "Nayla Suji",
          generasi: 12,
          asal: "Jepang",
          nama_panggilan: "Nayla",
          umur: 17,
          salam_perkenalan:
            "Moshi! moshi! Welcome Nayla-lalaland! Halo semuanya, bakkyun! Nama aku Nayla!",
          tanggal_bergabung: "18 November 2023",
          fanbase: "Naylands",
          kota_lahir: "Kumamoto",
          tanggal_lahir: "18 June 2007",
          nama_lengkap: "Nayla Suji Aurelia (ナイラ・スジ・アウレリア)",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/nayla_suji.jpg?v=20230116",
          username_ig: "@jkt48.nayla.s",
          username_tiktok: "@jkt48.nayla",
          username_x: "@SNayla_JKT48",
        },
        {
          id: 24,
          nama: "Nina Tutachia",
          generasi: 12,
          asal: "Bali",
          nama_panggilan: "Nachia",
          umur: 15,
          salam_perkenalan:
            "Si panda unyu yang selalu ceria. Halo aku Nachia, bikin kamu bahagia!",
          tanggal_bergabung: "18 November 2023",
          fanbase: "NiTuVers",
          kota_lahir: "Bali",
          tanggal_lahir: "16 October 2009",
          nama_lengkap: "Nina Tutachia Chapman",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/nina_tutachia.jpg?v=20230116",
          username_ig: "@jkt48.nachia.t",
          username_tiktok: "@jkt48.nachia",
          username_x: "@Nachia_JKT48",
        },
        {
          id: 25,
          nama: "Oline Manuel",
          generasi: 12,
          asal: "Jakarta",
          nama_panggilan: "Oline",
          umur: 17,
          salam_perkenalan: "Semangatku full terus, gas gas gas Oline!",
          tanggal_bergabung: "18 November 2023",
          fanbase: "Olinever",
          kota_lahir: "Jakarta",
          tanggal_lahir: "03 November 2007",
          nama_lengkap: "Oline Manuel Tjhai",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/oline_manuel.jpg?v=20230116",
          username_ig: "@jkt48.oline",
          username_tiktok: "@jkt48.oline",
          username_x: "@M_OlineJKT48",
        },
        {
          id: 26,
          nama: "Regina Wilian",
          generasi: 12,
          asal: "Surakarta",
          nama_panggilan: "Regie",
          umur: 15,
          salam_perkenalan:
            "Bagai kalium yang bereaksi dengan air, aku akan meledak dengan semangatku. Boom! Aku Regie.",
          tanggal_bergabung: "18 November 2023",
          fanbase: "Reginanska",
          kota_lahir: "Surakarta",
          tanggal_lahir: "10 December 2009",
          nama_lengkap: "Regina Wilian Hapsari",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/regina_wilian.jpg?v=20230116",
          username_ig: "@jkt48.regie",
          username_tiktok: "@jkt48.regie",
          username_x: "@Regie_JKT48",
        },
        {
          id: 27,
          nama: "Ribka Budiman",
          generasi: 12,
          asal: "Bandung",
          nama_panggilan: "Ribka",
          umur: 15,
          salam_perkenalan:
            "Mirror mirror on the wall, who's the sweetest in here? It's me Ribka!",
          tanggal_bergabung: "18 November 2023",
          fanbase: "Ribcalls",
          kota_lahir: "Bandung",
          tanggal_lahir: "13 January 2009",
          nama_lengkap: "Ribka Budiman",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/ribka_budiman.jpg?v=20230116",
          username_ig: "@jkt48.ribka",
          username_tiktok: "@jkt48.ribka",
          username_x: "@Ribka_JKT48",
        },
        {
          id: 28,
          nama: "Shabilqis Naila",
          generasi: 12,
          asal: "Jakarta",
          nama_panggilan: "Nala",
          umur: 16,
          salam_perkenalan:
            "Roar! Si singa pemberani yang siap menyemangati harimu. Hai, hai! Aku Nala.",
          tanggal_bergabung: "18 November 2023",
          fanbase: "Qistimewa",
          kota_lahir: "Jakarta",
          tanggal_lahir: "01 September 2008",
          nama_lengkap: "Shabilqis Naila Bustami",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/shabilqis_naila.jpg?v=20230116",
          username_ig: "@jkt48.nala",
          username_tiktok: "@jkt48.nala",
          username_x: "@Nala_JKT48",
        },
        {
          id: 29,
          nama: "Victoria Kimberly",
          generasi: 12,
          asal: "Jakarta",
          nama_panggilan: "Kimmy",
          umur: 14,
          salam_perkenalan:
            "Baby hamster yang lincah, aku akan berlari-lari di pikiranmu. Halo-ha, katakan Kimmy!",
          tanggal_bergabung: "18 November 2023",
          fanbase: "Victorian Era",
          kota_lahir: "Jakarta",
          tanggal_lahir: "08 March 2010",
          nama_lengkap: "Victoria Kimberly",
          universitas: "-",
          jurusan: "-",
          foto: "https://jkt48.com/profile/victoria_kimberly.jpg?v=20230116",
          username_ig: "@jkt48.kimmy",
          username_tiktok: "@jkt48.kimmy",
          username_x: "@Kimmy_JKT48",
        },
      ],
    };

    this.member = res.member;
    this.trainee = res.trainee;
  },

  methods: {
    sendID(type, i) {
      this.type = type;
      this.index = i;
    },
    clearSearch() {
      this.searchObject.nama = "";
      this.searchObject.umur = "";
      this.searchObject.generasi = "";
      this.searchObject.kota_lahir = "";
      this.searchObject.asal = "";
      this.searchObject.universitas = "";
    },
  },

  computed: {
    filteredMembers() {
      let searchParams = this.searchObject;

      return this.member.filter((item) => {
        return Object.entries(searchParams).every(([key, value]) => {
          const itemValue = String(item[key]).toLowerCase();
          const searchValue = String(value).toLowerCase();

          return (
            searchValue === "" ||
            (searchValue === "-"
              ? itemValue === searchValue
              : itemValue == searchValue)
          );
        });
      });
    },

    filteredTrainees() {
      let searchParams = this.searchObject;

      return this.trainee.filter((item) => {
        return Object.entries(searchParams).every(([key, value]) => {
          const itemValue = String(item[key]).toLowerCase();
          const searchValue = String(value).toLowerCase();

          return (
            searchValue === "" ||
            (searchValue === "-"
              ? itemValue === searchValue
              : itemValue == searchValue)
          );
        });
      });
    },
  },
};
</script>
